In [1]:
import numpy as np

In [3]:
integers = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
integers[0]

1

In [6]:
integers[4]

5

In [7]:
integers[0] = 11

In [8]:
integers[0] = 11.11

In [9]:
integers.dtype

dtype('int32')

In [11]:
small_integers = np.array(integers, dtype=np.int8)

In [12]:
small_integers

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [13]:
integers.nbytes

40

In [14]:
small_integers.nbytes

10

In [15]:
floats = np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,])

In [16]:
floats

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
floats.dtype

dtype('float64')

# Multidimentional arrays

In [18]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [19]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
nums[0]

array([1, 2, 3, 4, 5])

In [21]:
nums[1][4]

10

In [22]:
nums.ndim

2

In [23]:
multi_dim_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [24]:
multi_dim_arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
multi_dim_arr[0,2,2]

9

# creating arrays

In [37]:
list = [1,2,3,4,5,6,7,8,9,10]

In [38]:
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
arr_from_list = np.array(list)

In [40]:
arr_from_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
list2 = [1,2,3,-4,5.99032,-99.3,750]

In [42]:
list2

[1, 2, 3, -4, 5.99032, -99.3, 750]

In [45]:
arr_from_list2 = np.array(list2)

In [46]:
arr_from_list2

array([  1.     ,   2.     ,   3.     ,  -4.     ,   5.99032, -99.3    ,
       750.     ])

In [47]:
arr_from_list2.dtype

dtype('float64')

In [48]:
list3 = [1,"one",2,"two",3,"three",4,"four",5,"five"]

In [49]:
list3

[1, 'one', 2, 'two', 3, 'three', 4, 'four', 5, 'five']

In [50]:
arr_from_list3 = np.array(list3)

In [51]:
arr_from_list3

array(['1', 'one', '2', 'two', '3', 'three', '4', 'four', '5', 'five'],
      dtype='<U11')

In [52]:
tuple = (11,12,13,14,15,16,17,18,19,20)

In [53]:
tuple

(11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [54]:
arr_from_tuple = np.array(tuple)

In [55]:
arr_from_tuple

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
arr_from_tuple.dtype

dtype('int32')

In [65]:
multi_dim_list = [ [ [1,2,3],[4,5,6] ],[ [7,8,9],[10,11,12] ] ]

In [66]:
multi_dim_list

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [67]:
arr_from_multi_dim = np.array(multi_dim_list)

In [68]:
arr_from_multi_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])