# array creation

In [1]:
import numpy as np

In [2]:
integers_array = np.arange(10)

In [3]:
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
integers_array1 = np.arange(100,130)

In [5]:
integers_array1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [7]:
integers_array2 = np.arange(1,50,2)

In [8]:
integers_array2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [9]:
float_arr_0 = np.linspace(10,20)

In [10]:
float_arr_0

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [11]:
float_arr_1 = np.linspace(10,30,5)

In [12]:
float_arr_1

array([10., 15., 20., 25., 30.])

In [13]:
random_0 = np.random.rand(10)

In [14]:
random_0

array([0.4287963 , 0.39910394, 0.39980613, 0.01621452, 0.36464842,
       0.84392213, 0.32244984, 0.59860422, 0.74534687, 0.205233  ])

In [16]:
random_1 = np.random.rand(3,3)

In [17]:
random_1

array([[0.95742622, 0.63071573, 0.52715994],
       [0.81324914, 0.94292015, 0.24323309],
       [0.46781418, 0.63494355, 0.35935271]])

In [20]:
random_2 = np.random.randint(0,100,40)

In [21]:
random_2

array([32, 22, 43, 82, 61, 11, 93, 26, 48, 32, 58, 47, 15, 17, 62, 66, 99,
       35, 51, 48, 81, 39, 68, 33, 73, 93, 96, 35, 12, 25, 70, 86, 81, 37,
       30, 69, 36, 34, 89, 72])

In [22]:
zero_arr = np.zeros(5)

In [23]:
zero_arr

array([0., 0., 0., 0., 0.])

# 4 is row
# 2 is column

In [28]:
zero_arr_1 = np.zeros((4,2))


In [29]:
zero_arr_1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
ones_0 = np.ones(9)

In [31]:
ones_0

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
ones_1 = np.ones((4,6))

In [33]:
ones_1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
ones_3 = np.ones((3,5),dtype=int)

In [35]:
ones_3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
fill_arr_0 = np.empty(10,dtype=int)

In [37]:
fill_arr_0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
fill_arr_0.fill(11)

In [39]:
fill_arr_0

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [41]:
full_0 = np.full(10,5)

In [42]:
full_0

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [43]:
full_1 = np.full((3,4),8)

In [44]:
full_1

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [45]:
arr_0 = np.arange(20)

In [46]:
arr_0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
arr_1 = np.linspace((1,2),(10,20),10)

In [50]:
arr_1

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [51]:
arr_2 = np.full((2,2,2),10)

In [52]:
arr_2

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [53]:
np.shape(arr_0)

(20,)

In [54]:
np.shape(arr_1)

(10, 2)

In [55]:
np.shape(arr_2)

(2, 2, 2)

In [56]:
np.size(arr_0)

20

In [57]:
np.size(arr_1)

20

In [58]:
np.size(arr_2)

8