# adding , removing and sorting elements

In [1]:
import numpy as np

In [2]:
array_0 = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
array_0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
new_array_0 = np.insert(array_0,3,4)

In [10]:
new_array_0

array([ 1,  2,  3,  4,  4,  5,  6,  7,  8,  9, 10])

In [13]:
array_1 = np.array([1,2,3,4,5])

In [14]:
array_1

array([1, 2, 3, 4, 5])

In [15]:
new_array_1 = np.append(array_1,10)

In [16]:
new_array_1

array([ 1,  2,  3,  4,  5, 10])

In [17]:
new_array_3 = np.array([1,2,3,4,5])

In [18]:
new_array_3

array([1, 2, 3, 4, 5])

In [19]:
del_arr = np.delete(array_1,4)

In [20]:
del_arr

array([1, 2, 3, 4])

In [21]:
new_array_4 = np.random.randint(0,20,20)

In [22]:
new_array_4

array([ 1,  0,  2,  6,  2,  7,  3,  1, 17,  7, 14,  6, 19,  8, 10,  5, 16,
       18,  7, 10])

In [24]:
new_array_5 = np.sort(new_array_4)

In [25]:
new_array_5

array([ 0,  1,  1,  2,  2,  3,  5,  6,  6,  7,  7,  7,  8, 10, 10, 14, 16,
       17, 18, 19])

In [27]:
array_2 = np.array([[6,2,9,4,0,1],[2,6,3,9,0,4]])

In [28]:
array_2

array([[6, 2, 9, 4, 0, 1],
       [2, 6, 3, 9, 0, 4]])

In [29]:
new_array_6 = np.sort(array_2)

In [30]:
new_array_6

array([[0, 1, 2, 4, 6, 9],
       [0, 2, 3, 4, 6, 9]])

In [31]:
array_3 = ["black","green","blue","orange","pink"]

In [32]:
array_4 = np.array_3)

In [ ]:
new